version: "2"
services:
  postgres:
    image: postgres:alpine
#    command: "su - postgres -c 'pg_ctl -D \"/var/lib/postgresql/data\" -l /app/data/log start'"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    volumes:
      - database:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
  scribbli:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - "APP_ENV=${APP_ENV}"
      - "APP_KEY=${APP_KEY}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    depends_on:
      - postgres
    links:
      - postgres:postgres
volumes:
  database:
