# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sent_invite', models.BooleanField(default=False, verbose_name='sent invite')),
                ('ip_address', models.CharField(max_length=40, verbose_name='ip address')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
