# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('unik', models.CharField(max_length=32)),
                ('accepted', models.BooleanField(default=False)),
                ('sent_invite', models.BooleanField(default=False, verbose_name='sent invite')),
                ('date_expires', models.DateTimeField(default=datetime.datetime(2017, 2, 21, 22, 9, 6, 323584), verbose_name='date expires')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_accepted', models.DateTimeField(null=True, verbose_name='date accepted')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('phash', models.CharField(max_length=108, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
        ),
        migrations.AddField(
            model_name='alphainvitation',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', related_query_name='invite', to='siteapi.Writer'),
        ),
    ]
