# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import siteapi.models.alpha_invitation


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0004_auto_20170220_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphainvitation',
            name='date_expires',
            field=models.DateTimeField(default=siteapi.models.alpha_invitation.one_day_from_now, verbose_name='date expires'),
        ),
    ]
