# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0005_auto_20170220_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='token',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
