# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0006_writer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
