# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import siteapi.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0008_auto_20170224_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('is_public', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', upload_to=siteapi.models.image.generate_image_path, width_field='image_width')),
                ('image_width', models.FloatField(blank=True, null=True)),
                ('image_height', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('background', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='siteapi.UploadedImage')),
            ],
        ),
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='world',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worlds', related_query_name='world', to='siteapi.Writer'),
        ),
        migrations.AddField(
            model_name='world',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='siteapi.World'),
        ),
        migrations.AddField(
            model_name='world',
            name='thumbnail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='siteapi.UploadedImage'),
        ),
        migrations.AddField(
            model_name='world',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', related_query_name='world', to='siteapi.Universe'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', related_query_name='uploaded_image', to='siteapi.Writer'),
        ),
        migrations.AlterUniqueTogether(
            name='world',
            unique_together=set([('name', 'universe', 'slug')]),
        ),
    ]
