# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0011_auto_20170306_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=40)),
                ('nick', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', related_query_name='character', to='siteapi.Writer')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', related_query_name='race', to='siteapi.Writer')),
                ('world', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', related_query_name='race', to='siteapi.World')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', related_query_name='character', to='siteapi.Race'),
        ),
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', related_query_name='character', to='siteapi.World'),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together=set([('name', 'world', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set([('name', 'owner', 'slug')]),
        ),
    ]
