# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0014_auto_20170507_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='slug',
            field=models.CharField(default='scribbli', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', related_query_name='destination', to='siteapi.Destination'),
        ),
    ]
