# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0016_auto_20170827_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='avatar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_for_worlds', to='siteapi.UploadedImage'),
        ),
        migrations.AlterField(
            model_name='world',
            name='background',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_for_worlds', to='siteapi.UploadedImage'),
        ),
    ]
