# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapi', '0017_auto_20170829_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='avatar',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_for_destinations', to='siteapi.UploadedImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='siteapi.Destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='background',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_for_destinations', to='siteapi.UploadedImage'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='siteapi.World'),
        ),
        migrations.RemoveField(
            model_name='destination',
            name='is_region',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='region',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='thumbnail',
        ),
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together=set([('name', 'world')]),
        ),
    ]
