# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-01 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteapi', '0019_auto_20170930_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_for_characters', to='siteapi.UploadedImage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='siteapi.Race'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='siteapi.World'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_public',
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set([('name', 'owner')]),
        ),
    ]
