# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-01 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteapi', '0020_auto_20171001_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(related_name='stories', to='siteapi.StoryTag'),
        ),
        migrations.AddField(
            model_name='storystatus',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storystatus',
            name='slug',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storytag',
            name='icon',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storytag',
            name='slug',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='siteapi.Destination'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='siteapi.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='characters',
            field=models.ManyToManyField(related_name='stories', to='siteapi.Character'),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='stories', to='siteapi.StoryStatus'),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyposts', to='siteapi.Chapter'),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='characters',
            field=models.ManyToManyField(related_name='in_posts', to='siteapi.Character'),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storypost',
            name='pov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='siteapi.Character'),
        ),
        migrations.AlterField(
            model_name='storystatus',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storystatus',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storytag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storytag',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='is_closed',
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set([('name', 'story')]),
        ),
        migrations.RemoveField(
            model_name='story',
            name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together=set([('name', 'owner')]),
        ),
    ]
